# Generated by Django 4.2.3 on 2023-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='about me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(default='nairobi'),
        ),
    ]
