# Generated by Django 4.2.3 on 2023-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_follower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_post', to='base.like'),
        ),
    ]
