# Generated by Django 4.2.3 on 2023-08-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
