# Generated by Django 4.2.3 on 2023-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_like_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
