# Generated by Django 4.2.3 on 2023-08-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_profile_following_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following_count',
        ),
    ]
