# Generated by Django 4.2.3 on 2023-08-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_follower_user_alter_follower_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
