# Generated by Django 4.2.3 on 2023-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'single'), ('in a Relationship', 'In A Relationship'), ('engaged', 'engaged'), ('married', 'married')], default='none', max_length=50),
        ),
    ]
