# Generated by Django 4.2.3 on 2023-08-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_profile_bio_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profile', 'liked_object')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
