# Generated by Django 4.2.3 on 2023-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_like_unique_together_alter_like_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos'),
        ),
    ]
